name: gal
description: Gal is a Flutter plugin for handle native gallary apps. Easily open or save media files to native gallery apps.
version: 1.1.2
homepage: https://pub.dev/packages/gal
repository: https://github.com/natsuk4ze/gal

topics:
 - gallery
 - video
 - image
 - plugin
 - util

screenshots:
 - description: 'Screenshot of example app in Android.'
   path: example/assets/android_example.gif
 - description: 'Screenshot of example app in iOS.'
   path: example/assets/ios_example.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  android_intent_plus: ^4.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.gal
        pluginClass: GalPlugin
      ios:
        pluginClass: GalPlugin