name: gal
description: Flutter plugin for handle native gallary apps.
version: 0.0.1
homepage: https://github.com/Midori-Design-Studio/gal
repository: https://github.com/Midori-Design-Studio/gal

topics:
 - gallery
 - video
 - plugin

screenshots:
 - description: 'Screenshot of example app.'
   path: example\assets\screenshot.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  android_intent_plus: ^4.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.gal
        pluginClass: GalPlugin
      ios:
        pluginClass: GalPlugin