name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31]
        target: [google_apis]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      - name: Install Flutter dependencies
        run: |
          flutter pub get ./example

      - name: Run integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-options: "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
          working-directory: ./example
          script: |
            echo ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=600 >> $GITHUB_ENV
            flutter test integration_test/integration_test.dart
