name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'beta'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze
    
    - name: Install example dependencies
      run: |
        cd example
        flutter pub get

    - name: Analyze example code
      run: |
        cd example
        flutter analyze

    - name: Run integration tests
      run: |
        cd example
        flutter test test/integration_test.dart
